server:
  servlet:
    context-path: /booksale
  error:
    whitelabel:
      enable: false

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/booksale
    username: springstudent
    password: springstudent
  jpa:
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#logging:
#   level:
#     root: WARN
#    org:
#      hibernate:
#        SQL: debug
#    org.springframework.security: DEBUG